// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-HO-ojb_0rnclefu0d3DCfy6pDn2NSOk',
    appId: '1:606184294241:web:dbd579eba44b8da2d92720',
    messagingSenderId: '606184294241',
    projectId: 'laravel-forge-ac6ae',
    authDomain: 'laravel-forge-ac6ae.firebaseapp.com',
    storageBucket: 'laravel-forge-ac6ae.appspot.com',
    measurementId: 'G-YNJC61HB79',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMt95uZqcgoUr-U3yPlV3yIUUV4l-x5So',
    appId: '1:606184294241:android:71ff42cbbc25ad31d92720',
    messagingSenderId: '606184294241',
    projectId: 'laravel-forge-ac6ae',
    storageBucket: 'laravel-forge-ac6ae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdn3g95EjlAYjDR4gSdGtSTGQjuGumcbE',
    appId: '1:606184294241:ios:46743339371829f9d92720',
    messagingSenderId: '606184294241',
    projectId: 'laravel-forge-ac6ae',
    storageBucket: 'laravel-forge-ac6ae.appspot.com',
    iosClientId: '606184294241-3vneqcvvb87gavger4e37kpvdpnq9b6p.apps.googleusercontent.com',
    iosBundleId: 'com.algoriza.forge',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdn3g95EjlAYjDR4gSdGtSTGQjuGumcbE',
    appId: '1:606184294241:ios:46743339371829f9d92720',
    messagingSenderId: '606184294241',
    projectId: 'laravel-forge-ac6ae',
    storageBucket: 'laravel-forge-ac6ae.appspot.com',
    iosClientId: '606184294241-3vneqcvvb87gavger4e37kpvdpnq9b6p.apps.googleusercontent.com',
    iosBundleId: 'com.algoriza.forge',
  );
}
